/**
* This file should be include to clear up all macro declared in def-macro.inc
*/

#undef var
#undef auto
#undef dec_var

#undef list
#undef dec_list

#undef cin
#undef cout

#undef if
#undef else
#undef repeat
#undef repeat_until
#undef while
#undef do

#undef return
#undef continue
#undef break

#undef __procedure_arg_proccode
#undef __procedure_arg_id
#undef __procedure_arg_id_quoted
#undef __procedure_arg_name
#undef __procedure_arg_default

#undef __procedure_arg_lambda_arg
#undef __procedure_arg_lambda_passing_arg

#undef __procedure_arg_call_arg
#undef __procedure_arg_call_check
#undef __procedure_arg_call_mount
    
#undef __procedure_arg_init_block    

#undef procedure

// vim: filetype=cpp

